name: release

on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install --save-dev
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: David Jakowenko
          GIT_AUTHOR_EMAIL: jakowenko@gmail.com
          GIT_COMMITTER_NAME: David Jakowenko
          GIT_COMMITTER_EMAIL: jakowenko@gmail.com
        run: npx semantic-release
